### ISSUE TITLE
Zend\Code\Exception\RuntimeException  No tokens were provided

### ISSUE THREAD

**Issue by jtsternberg** [ralphschindler/Namespacer#1]
Tried using this library, but got this error each time.

```
$ php namespacer.phar map --mapfile map.php --source .
======================================================================
   The application has thrown an exception!
======================================================================
 Zend\Code\Exception\RuntimeException
 No tokens were provided
----------------------------------------------------------------------
phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-code/Zend/Code/Scanner/TokenArrayScanner.php:2
#0 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-code/Zend/Code/Scanner/TokenArrayScanner.php(2): Zend\Code\Scanner\TokenArrayScanner->scan()
#1 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/src/Namespacer/Model/Mapper.php(2): Zend\Code\Scanner\TokenArrayScanner->getClassNames()
#2 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/src/Namespacer/Model/Mapper.php(2): Namespacer\Model\Mapper->getMapDataForFile('/Users/JT/Sites...')
#3 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/src/Namespacer/Controller/Controller.php(2): Namespacer\Model\Mapper->getMapDataForDirectory('.')
#4 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(2): Namespacer\Controller\Controller->createMapAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#7 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(2): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 phar:///Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar/namespacer.php(2): Zend\Mvc\Application->run()
#15 /Users/JT/Sites/dsgnwrks.pro/wp-content/mu-plugins/cmb2/namespacer.phar(7): require('phar:///Users/J...')
#16 {main}
======================================================================
   Previous Exception(s):
======================================================================
```

**Comment by mbelatar** [comment]
Hi,
Just delete all Empty Files.
Effacez les fichiers vides.
